version: "3.8"

services:
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "5050:5050"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://admin:PassWord@db:5432/books6
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: lab6
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PassWord
      - POSTGRES_DB=books6

volumes:
  postgres_data:
